---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/aleampo8/staging.aleamodular.com
    - /bin/cp wp-content/themes/theratio-child/functions.php "$DEPLOYPATH/wp-content/themes/theratio-child/functions.php"
    - /bin/cp wp-content/mu-plugins/alea-quiet-theratio-warnings.php "$DEPLOYPATH/wp-content/mu-plugins/alea-quiet-theratio-warnings.php"
